name: Ubuntu
# Qt官方没有linux平台的x86包
on: 
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        qt_ver: [5.9.9,5.12.10,5.15.2]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.2
        with:
          version: ${{ matrix.qt_ver }}
          modules: 'qtcharts'
          cached: 'false'

      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: build ubuntu
        run: |
          mkdir build && cd build
          cmake ..
          make
          
      # 上传artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}.zip
          path: bin/release/${{ env.targetName }}.app
